# Generated by Django 6.0.5 on 2026-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the external job application page",
                max_length=500,
                null=True,
            ),
        ),
    ]
