# Generated by Django 6.0.5 on 2026-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_application_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly salary in Rupees (₹)",
                max_digits=10,
            ),
        ),
    ]
