# Generated by Django 6.0.5 on 2026-06-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_salary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedJob",
        ),
    ]
