# Generated by Django 6.0.5 on 2026-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_delete_savedjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
