# Generated by Django 6.0.5 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(
                help_text="Annual salary (e.g., 12-22 LPA)", max_length=100
            ),
        ),
    ]
