# Generated by Django 6.0.5 on 2026-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[("IT", "IT"), ("Non-IT", "Non-IT")],
                default="IT",
                max_length=10,
            ),
        ),
    ]
